/** 悬浮框中英文案 */
export type KbQaLang = 'zh' | 'en'

const zh = {
  title: '问答助手',
  fab: '打开问答助手',
  minimize: '收起',
  newChat: '新建对话',
  placeholder: '输入你的问题…',
  send: '发送',
  stop: '停止',
  welcome: '了解 J2Agent：一个把 Agent、工具、企业知识与可靠运行时连接起来的 AI 工作平台。',
  connecting: '连接中',
  thinking: '思考中',
  answering: '正在回答',
  source: '来源',
  emptyConfig: '请先在 config.ts 中配置 backendBaseUrl 与 apiKey',
  copy: '复制',
  copied: '已复制',
  poweredBy: 'Powered by',
  scrollToBottom: '回到底部',
  /** 对齐 j2a：生成式内容核实提示 */
  disclaimer: '* 内容由生成式人工智能大模型产生，请注意核实',
  thinkingTitle: '深度思考',
  hotQuestions: '热门问题',
  refreshHotQuestions: '换一批',
  examples: [
    'J2Agent 的整体架构是怎样的？',
    'RAG 融合检索如何工作？',
    '如何开发一个 J2Agent Agent？'
  ],
  askCustomPlaceholder: '或输入自定义回答…',
  askSend: '提交回答',
  askEmpty: '请输入回答内容'
}

const en: typeof zh = {
  title: 'Q&A Assistant',
  fab: 'Open Q&A assistant',
  minimize: 'Collapse',
  newChat: 'New chat',
  placeholder: 'Ask a question…',
  send: 'Send',
  stop: 'Stop',
  welcome: 'Explore J2Agent, an AI work platform connecting agents, tools, enterprise knowledge, and a reliable runtime.',
  connecting: 'Connecting',
  thinking: 'Thinking',
  answering: 'Answering',
  source: 'Sources',
  emptyConfig: 'Please set backendBaseUrl and apiKey in config.ts',
  copy: 'Copy',
  copied: 'Copied',
  poweredBy: 'Powered by',
  scrollToBottom: 'Scroll to bottom',
  disclaimer: '* Content is generated by a generative AI model. Please verify it.',
  thinkingTitle: 'Deep thinking',
  hotQuestions: 'Popular questions',
  refreshHotQuestions: 'Refresh',
  examples: [
    'How is the J2Agent platform structured?',
    'How does hybrid RAG retrieval work?',
    'How do I build a J2Agent agent?'
  ],
  askCustomPlaceholder: 'Or type a custom answer…',
  askSend: 'Submit answer',
  askEmpty: 'Please enter an answer'
}

export type KbQaCopy = typeof zh

export function kbQaText(lang: KbQaLang): KbQaCopy {
  return lang === 'en' ? en : zh
}
